<?php

/**
 * Mapa canônico dos 73 livros da Bíblia Católica, indexado pelo nome exato
 * usado em bibliaAveMaria.json ("nome" de cada livro). A ordem de exibição
 * (order) segue a ordem em que os livros aparecem no próprio JSON fonte,
 * que já corresponde a uma ordenação válida do cânone católico completo.
 */
return [
    // Antigo Testamento
    'Gênesis' => ['slug' => 'genesis', 'testament' => 'antigo', 'category' => 'pentateuco', 'order' => 1, 'abbr' => 'Gn', 'deutero' => false],
    'Êxodo' => ['slug' => 'exodo', 'testament' => 'antigo', 'category' => 'pentateuco', 'order' => 2, 'abbr' => 'Ex', 'deutero' => false],
    'Levítico' => ['slug' => 'levitico', 'testament' => 'antigo', 'category' => 'pentateuco', 'order' => 3, 'abbr' => 'Lv', 'deutero' => false],
    'Números' => ['slug' => 'numeros', 'testament' => 'antigo', 'category' => 'pentateuco', 'order' => 4, 'abbr' => 'Nm', 'deutero' => false],
    'Deuteronômio' => ['slug' => 'deuteronomio', 'testament' => 'antigo', 'category' => 'pentateuco', 'order' => 5, 'abbr' => 'Dt', 'deutero' => false],
    'Josué' => ['slug' => 'josue', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 6, 'abbr' => 'Js', 'deutero' => false],
    'Juízes' => ['slug' => 'juizes', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 7, 'abbr' => 'Jz', 'deutero' => false],
    'Rute' => ['slug' => 'rute', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 8, 'abbr' => 'Rt', 'deutero' => false],
    'I Samuel' => ['slug' => '1-samuel', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 9, 'abbr' => '1Sm', 'deutero' => false],
    'II Samuel' => ['slug' => '2-samuel', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 10, 'abbr' => '2Sm', 'deutero' => false],
    'I Reis' => ['slug' => '1-reis', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 11, 'abbr' => '1Rs', 'deutero' => false],
    'II Reis' => ['slug' => '2-reis', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 12, 'abbr' => '2Rs', 'deutero' => false],
    'I Crônicas' => ['slug' => '1-cronicas', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 13, 'abbr' => '1Cr', 'deutero' => false],
    'II Crônicas' => ['slug' => '2-cronicas', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 14, 'abbr' => '2Cr', 'deutero' => false],
    'Esdras' => ['slug' => 'esdras', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 15, 'abbr' => 'Ed', 'deutero' => false],
    'Neemias' => ['slug' => 'neemias', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 16, 'abbr' => 'Ne', 'deutero' => false],
    'Tobias' => ['slug' => 'tobias', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 17, 'abbr' => 'Tb', 'deutero' => true],
    'Judite' => ['slug' => 'judite', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 18, 'abbr' => 'Jt', 'deutero' => true],
    'Ester' => ['slug' => 'ester', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 19, 'abbr' => 'Et', 'deutero' => false],
    'Jó' => ['slug' => 'jo', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 20, 'abbr' => 'Jó', 'deutero' => false],
    'Salmos' => ['slug' => 'salmos', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 21, 'abbr' => 'Sl', 'deutero' => false],
    'I Macabeus' => ['slug' => '1-macabeus', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 22, 'abbr' => '1Mc', 'deutero' => true],
    'II Macabeus' => ['slug' => '2-macabeus', 'testament' => 'antigo', 'category' => 'historicos', 'order' => 23, 'abbr' => '2Mc', 'deutero' => true],
    'Provérbios' => ['slug' => 'proverbios', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 24, 'abbr' => 'Pr', 'deutero' => false],
    'Eclesiastes' => ['slug' => 'eclesiastes', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 25, 'abbr' => 'Ec', 'deutero' => false],
    'Cântico dos Cânticos' => ['slug' => 'cantico-dos-canticos', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 26, 'abbr' => 'Ct', 'deutero' => false],
    'Sabedoria' => ['slug' => 'sabedoria', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 27, 'abbr' => 'Sb', 'deutero' => true],
    'Eclesiástico' => ['slug' => 'eclesiastico', 'testament' => 'antigo', 'category' => 'sapienciais', 'order' => 28, 'abbr' => 'Eclo', 'deutero' => true],
    'Isaías' => ['slug' => 'isaias', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 29, 'abbr' => 'Is', 'deutero' => false],
    'Jeremias' => ['slug' => 'jeremias', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 30, 'abbr' => 'Jr', 'deutero' => false],
    'Lamentações' => ['slug' => 'lamentacoes', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 31, 'abbr' => 'Lm', 'deutero' => false],
    'Baruc' => ['slug' => 'baruc', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 32, 'abbr' => 'Br', 'deutero' => true],
    'Ezequiel' => ['slug' => 'ezequiel', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 33, 'abbr' => 'Ez', 'deutero' => false],
    'Daniel' => ['slug' => 'daniel', 'testament' => 'antigo', 'category' => 'profetas_maiores', 'order' => 34, 'abbr' => 'Dn', 'deutero' => false],
    'Oséias' => ['slug' => 'oseias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 35, 'abbr' => 'Os', 'deutero' => false],
    'Joel' => ['slug' => 'joel', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 36, 'abbr' => 'Jl', 'deutero' => false],
    'Amós' => ['slug' => 'amos', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 37, 'abbr' => 'Am', 'deutero' => false],
    'Abdias' => ['slug' => 'abdias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 38, 'abbr' => 'Ab', 'deutero' => false],
    'Jonas' => ['slug' => 'jonas', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 39, 'abbr' => 'Jn', 'deutero' => false],
    'Miquéias' => ['slug' => 'miqueias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 40, 'abbr' => 'Mq', 'deutero' => false],
    'Naum' => ['slug' => 'naum', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 41, 'abbr' => 'Na', 'deutero' => false],
    'Habacuc' => ['slug' => 'habacuc', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 42, 'abbr' => 'Hc', 'deutero' => false],
    'Sofonias' => ['slug' => 'sofonias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 43, 'abbr' => 'Sf', 'deutero' => false],
    'Ageu' => ['slug' => 'ageu', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 44, 'abbr' => 'Ag', 'deutero' => false],
    'Zacarias' => ['slug' => 'zacarias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 45, 'abbr' => 'Zc', 'deutero' => false],
    'Malaquias' => ['slug' => 'malaquias', 'testament' => 'antigo', 'category' => 'profetas_menores', 'order' => 46, 'abbr' => 'Ml', 'deutero' => false],

    // Novo Testamento
    'São Mateus' => ['slug' => 'mateus', 'testament' => 'novo', 'category' => 'evangelhos', 'order' => 47, 'abbr' => 'Mt', 'deutero' => false],
    'São Marcos' => ['slug' => 'marcos', 'testament' => 'novo', 'category' => 'evangelhos', 'order' => 48, 'abbr' => 'Mc', 'deutero' => false],
    'São Lucas' => ['slug' => 'lucas', 'testament' => 'novo', 'category' => 'evangelhos', 'order' => 49, 'abbr' => 'Lc', 'deutero' => false],
    'São João' => ['slug' => 'joao', 'testament' => 'novo', 'category' => 'evangelhos', 'order' => 50, 'abbr' => 'Jo', 'deutero' => false],
    'Atos dos Apóstolos' => ['slug' => 'atos-dos-apostolos', 'testament' => 'novo', 'category' => 'atos', 'order' => 51, 'abbr' => 'At', 'deutero' => false],
    'Romanos' => ['slug' => 'romanos', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 52, 'abbr' => 'Rm', 'deutero' => false],
    'I Coríntios' => ['slug' => '1-corintios', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 53, 'abbr' => '1Co', 'deutero' => false],
    'II Coríntios' => ['slug' => '2-corintios', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 54, 'abbr' => '2Co', 'deutero' => false],
    'Gálatas' => ['slug' => 'galatas', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 55, 'abbr' => 'Gl', 'deutero' => false],
    'Efésios' => ['slug' => 'efesios', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 56, 'abbr' => 'Ef', 'deutero' => false],
    'Filipenses' => ['slug' => 'filipenses', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 57, 'abbr' => 'Fl', 'deutero' => false],
    'Colossenses' => ['slug' => 'colossenses', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 58, 'abbr' => 'Cl', 'deutero' => false],
    'I Tessalonicenses' => ['slug' => '1-tessalonicenses', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 59, 'abbr' => '1Ts', 'deutero' => false],
    'II Tessalonicenses' => ['slug' => '2-tessalonicenses', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 60, 'abbr' => '2Ts', 'deutero' => false],
    'I Timóteo' => ['slug' => '1-timoteo', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 61, 'abbr' => '1Tm', 'deutero' => false],
    'II Timóteo' => ['slug' => '2-timoteo', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 62, 'abbr' => '2Tm', 'deutero' => false],
    'Tito' => ['slug' => 'tito', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 63, 'abbr' => 'Tt', 'deutero' => false],
    'Filêmon' => ['slug' => 'filemon', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 64, 'abbr' => 'Fm', 'deutero' => false],
    'Hebreus' => ['slug' => 'hebreus', 'testament' => 'novo', 'category' => 'cartas_paulinas', 'order' => 65, 'abbr' => 'Hb', 'deutero' => false],
    'São Tiago' => ['slug' => 'tiago', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 66, 'abbr' => 'Tg', 'deutero' => false],
    'I São Pedro' => ['slug' => '1-pedro', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 67, 'abbr' => '1Pe', 'deutero' => false],
    'II São Pedro' => ['slug' => '2-pedro', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 68, 'abbr' => '2Pe', 'deutero' => false],
    'I São João' => ['slug' => '1-joao', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 69, 'abbr' => '1Jo', 'deutero' => false],
    'II São João' => ['slug' => '2-joao', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 70, 'abbr' => '2Jo', 'deutero' => false],
    'III São João' => ['slug' => '3-joao', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 71, 'abbr' => '3Jo', 'deutero' => false],
    'São Judas' => ['slug' => 'judas', 'testament' => 'novo', 'category' => 'cartas_catolicas', 'order' => 72, 'abbr' => 'Jd', 'deutero' => false],
    'Apocalipse' => ['slug' => 'apocalipse', 'testament' => 'novo', 'category' => 'apocalipse', 'order' => 73, 'abbr' => 'Ap', 'deutero' => false],
];
